language: python
python:
- '3.6'
env:
- TOXENV=py36
- TOXENV=flake8
- TOXENV=build
install:
- pip install tox
script: tox
services:
- postgresql
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: rmb938
  password:
    secure: kmyrXVrwj6et8AiC9a6llLU26gIFPVa/DJSGt9uluZpI2RLrNCPLJhJYR81y1f8muNw1wvIubxyeXDYC1206kiSRZ8cyV6amvpUnXVuvB/YYlCwFMlrdJbbsKBtz3IepfoZVPiZa6YQLeuWFde9s7v43uxMOSx28eEDrZ5PporjTw1BWHK1OSaZ9iM9Z+HOWt6qizDfldJo27IJh5/505pDBQTVfP+2Xk8r2sIY5i+BpBkWfLgGfgnRfT4TaPPIZcyhjIMOIUlt9vy/Fmgm2PJeOaEk5L4cD7JOiQAxSyVcrAFKCg3u+xEy3609dmg2JeqF0FFfn4qmMoaAYX78qihbZONoKKYRq0i/iydx9QtgMkFovz/N8TzdK5vpfxccnXiNKTylMrO1RrD+kf3wKdl+m8v2yk7ewi9DXejnxhDRl+ndTiE06ONXQCMmD1ITF/zW9vdcvpWKLwETzbjJbHWRahIHCosk8Idaa8+Wu+MQoLXUJRA6JRRbUJVKCR5ANb38uPTnI4Wu+HzyJmE+9mAEiUZmPN+5EQdIaDUcypC3iPKddVD9x6aQJnWz9xlcParfjSGQaI5fHAUSvth7iBh6DeVDhJMyrVtwo4rJNF0OgiaKOtiLoV+vqvCBi5Dqy25ZI6MxIWC1MeP+lt0KpjIBO6o5yXtArAH1XlCYgieI=
  on:
    tags: true
